Bail if the vagrant build fails

diff --git a/vagrant b/vagrant
--- a/vagrant
+++ b/vagrant
@@ -54,6 +54,12 @@ rm build.tgz
 cd build
 rm -rf .git
 make
+
+if [ $? -ne 0 ]; then
+    echo 'Build failed!' >&2
+    exit 1
+fi
+
 cd ..
 
 mv build "$1"
